%% Author: Chris Conatser
%  Date: 2015/8/12
%  Last edited: 2015/8/12
%
% This script reads data from the Google Drive copy of the DataTable.csv
% file written by remotedata.m and sends it to https://plot.ly to render time series
% graphs which are embedded in the Hydroinformatics website at http://research.engr.oregonstate.edu/hydroinformatics/article/avery-data.

%% List everyone here who wants to recieve a text or email when action-requiring events occur
% (see send_msg.m)

recipients = {'816-868-5314'};
carrier    = 'Verizon';

%% ---- Set up workspace and load data ---- %%

cd('C:/Users/Chris/Google Drive/OGSIR/Data/');

diary('Log.txt')                                            % open Log and append command window outputs

DataTable = readtable('DataTableReplacement.csv');          % read csv into table of variables


Newest = size(DataTable,1);                                 % Label important timestamps
Previous = (Newest-1);
TwelveHoursAgo = (Newest-48);
OneWeekAgo = (Newest-672);

% %% ---- Trim egregiously bad data ---- %%
% 
% if DataTable.AirTmp(OneWeekAgo:Newest)<(-15) || DataTable.AirTmp(OneWeekAgo:Newest)>45        % trim spurious temps
%     DataTable.AirTmp(OneWeekAgo:Newest) = 'NAN'
% end
% 
% if DataTable.BarPress(:)<970 || DataTable.BarPress(:)>1040  % trim spurious pressures
%     DataTable.BarPress(:) = 'NAN'
% end

WebData = DataTable(OneWeekAgo:Newest,:);

writetable(WebData,'WebData.csv');            % write clean csv

% Send text messages to notify of important events
% 
% if (all(DataTable.Rain(TwelveHoursAgo:Previous)<1) && ( DataTable.Rain(Newest) > 1)    % If it's starting to rain, send a text
%     subject    = 'It''s raining at the bioswales!';         % (recipients and carrier defined at top of file;
%     message    = 'It''s raining at the bioswales!';         % text is sent from ogsir.osu@gmail.com)
%     send_msg(recipients, subject, message, carrier);        % send_message.m should be kept in the same folder as this file
% end
%
%% Write new data to OGSIR Weather plot
    
% Get figure documentation: https://plot.ly/matlab/get-requests/
% Add data documentation: https://plot.ly/matlab/file-options/

% Learn about API authentication here: https://plot.ly/matlab/getting-started
% Find your api_key here: https://plot.ly/settings/api

signin('OGSIR.OSU', 'jg3xxmsgku');


%% Weather Plot

trace1 = struct(...
  'x', {  DataTable.Time(OneWeekAgo:Newest) }, ...
  'y', DataTable.NetRad_Wm2(OneWeekAgo:Newest), ...
  'mode', 'lines+markers', ...
  'name', 'Net Solar Radiation (W/m^2)', ...
  'marker', struct(...
    'color', 'rgb(241, 194, 50)', ...
    'size', 6, ...
    'symbol', 'circle', ...
    'line', struct(...
      'color', 'rgb(241, 194, 50)', ...
      'width', 0), ...
    'opacity', 0.8, ...
    'maxdisplayed', 672), ...
  'line', struct(...
    'color', 'rgb(241, 194, 50)', ...
    'width', 2, ...
    'dash', 'solid', ...
    'shape', 'linear'), ...
  'fill', 'none', ...
  'opacity', 0.8, ...
  'yaxis', 'y4', ...
  'visible', true, ...
  'xsrc', 'DataTable.Time', ...
  'ysrc', 'DataTable.NetRad_Wm2', ...
  'type', 'scatter');
trace2 = struct(...
  'x', {  DataTable.Time(OneWeekAgo:Newest) }, ...
  'y', DataTable.WndSpd(OneWeekAgo:Newest), ...
  'mode', 'lines+markers', ...
  'name', 'Wind Speed (km/h)', ...
  'marker', struct(...
    'color', 'rgb(69, 129, 142)', ...
    'size', 6, ...
    'symbol', 'circle', ...
    'line', struct(...
      'color', 'rgb(69, 129, 142)', ...
      'width', 0), ...
    'opacity', 1, ...
    'maxdisplayed', 672), ...
  'line', struct(...
    'color', 'rgb(69, 129, 142)', ...
    'width', 2, ...
    'dash', 'solid', ...
    'shape', 'linear'), ...
  'fill', 'none', ...
  'opacity', 1, ...
  'yaxis', 'y5', ...
  'xsrc', 'DataTable.Time', ...
  'ysrc', 'DataTable.WndSpd', ...
  'type', 'scatter');
trace3 = struct(...
  'x', {  DataTable.Time(OneWeekAgo:Newest) }, ...
  'y', DataTable.WndDir(OneWeekAgo:Newest), ...
  'mode', 'lines+markers', ...
  'name', 'Wind Direction (&deg;E of N)', ...
  'marker', struct(...
    'color', 'rgb(166, 77, 121)', ...
    'size', 6, ...
    'symbol', 'dot', ...
    'line', struct(...
      'color', 'rgb(166, 77, 121)', ...
      'width', 0)), ...
  'line', struct(...
    'color', 'rgb(166, 77, 121)', ...
    'width', 2, ...
    'dash', 'solid', ...
    'shape', 'linear'), ...
  'fill', 'none', ...
  'opacity', 0.7, ...
  'yaxis', 'y8', ...
  'xsrc', 'DataTable.Time', ...
  'ysrc', 'DataTable.WndDir', ...
  'type', 'scatter');
trace4 = struct(...
  'x', {  DataTable.Time(OneWeekAgo:Newest) }, ...
  'y', DataTable.AirTmp(OneWeekAgo:Newest), ...
  'mode', 'lines+markers', ...
  'name', 'Air Temperature (&deg;C)', ...
  'marker', struct(...
    'color', 'rgb(224, 102, 102)', ...
    'size', 6, ...
    'symbol', 'dot', ...
    'line', struct(...
      'color', 'rgb(224, 102, 102)', ...
      'width', 0)), ...
  'line', struct(...
    'color', 'rgb(224, 102, 102)', ...
    'width', 2, ...
    'dash', 'solid', ...
    'shape', 'linear'), ...
  'fill', 'none', ...
  'opacity', 1, ...
  'yaxis', 'y3', ...
  'xsrc', 'DataTable.Time', ...
  'ysrc', 'DataTable.AirTmp', ...
  'type', 'scatter');
trace5 = struct(...
  'x', {  DataTable.Time(OneWeekAgo:Newest) }, ...
  'y', DataTable.RelHum(OneWeekAgo:Newest), ...
  'mode', 'lines+markers', ...
  'name', 'Relative Humidity (%)', ...
  'marker', struct(...
    'color', 'rgb(159, 197, 232)', ...
    'size', 6, ...
    'symbol', 'dot', ...
    'line', struct(...
      'color', 'rgb(159, 197, 232)', ...
      'width', 0)), ...
  'line', struct(...
    'color', 'rgb(159, 197, 232)', ...
    'width', 2, ...
    'dash', 'solid', ...
    'shape', 'linear'), ...
  'fill', 'none', ...
  'opacity', 0.9, ...
  'yaxis', 'y7', ...
  'xsrc', 'DataTable.Time', ...
  'ysrc', 'DataTable.RelHum', ...
  'type', 'scatter');
trace6 = struct(...
  'x', {  DataTable.Time(OneWeekAgo:Newest) }, ...
  'y', DataTable.BarPress(OneWeekAgo:Newest), ...
  'mode', 'lines+markers', ...
  'name', 'Atmospheric Pressure (mb)', ...
  'marker', struct(...
    'color', 'rgba(68, 68, 68, 0.49)', ...
    'size', 6, ...
    'symbol', 'dot', ...
    'line', struct(...
      'color', 'rgba(68, 68, 68, 0.49)', ...
      'width', 0)), ...
  'line', struct(...
    'color', 'rgba(68, 68, 68, 0.49)', ...
    'width', 2, ...
    'dash', 'solid', ...
    'shape', 'linear'), ...
  'fill', 'none', ...
  'opacity', 0.8, ...
  'yaxis', 'yaxis', ...
  'xsrc', 'DataTable.Time', ...
  'ysrc', 'DataTable.BarPress', ...
  'type', 'scatter');
trace7 = struct(...
  'x', {  DataTable.Time(OneWeekAgo:Newest) }, ...
  'y', DataTable.Rain(OneWeekAgo:Newest), ...
  'mode', 'lines+markers', ...
  'name', 'Rain (mm)', ...
  'marker', struct(...
    'color', 'rgb(5, 10, 172)', ...
    'size', 6, ...
    'symbol', 'dot', ...
    'line', struct(...
      'color', 'rgb(5, 10, 172)', ...
      'width', 0)), ...
  'line', struct(...
    'color', 'rgb(5, 10, 172)', ...
    'width', 2, ...
    'dash', 'solid', ...
    'shape', 'linear'), ...
  'fill', 'none', ...
  'opacity', 1, ...
  'yaxis', 'y2', ...
  'xsrc', 'DataTable.Time', ...
  'ysrc', 'DataTable.Rain', ...
  'type', 'scatter');
data = {trace1, trace2, trace3, trace4, trace5, trace6, trace7};
layout = struct(...
    'title', 'Weather', ...
    'titlefont', struct(...
      'family', '"Open sans", verdana, arial, sans-serif', ...
      'size', 24, ...
      'color', '#444'), ...
    'font', struct(...
      'family', '"Open sans", verdana, arial, sans-serif', ...
      'size', 12, ...
      'color', '#444'), ...
    'autosize', true, ...
    'width', 1368, ...
    'height', 871, ...
    'xaxis', struct(...
      'titlefont', struct(...
        'family', '"Open sans", verdana, arial, sans-serif', ...
        'size', 14, ...
        'color', '#444'), ...
      'range', [1.43866895889e+12, 1.43936454111e+12], ...
      'domain', [0, 1], ...
      'type', 'date', ...
      'rangemode', 'normal', ...
      'autorange', true, ...
      'showgrid', true, ...
      'zeroline', true, ...
      'showline', false, ...
      'nticks', 0, ...
      'ticks', '', ...
      'showticklabels', true, ...
      'tickangle', 'auto', ...
      'tickfont', struct(...
        'family', '"Open sans", verdana, arial, sans-serif', ...
        'size', 12, ...
        'color', '#444'), ...
      'gridcolor', 'rgb(68, 68, 68)', ...
      'gridwidth', 1, ...
      'zerolinecolor', '#444', ...
      'zerolinewidth', 1, ...
      'linecolor', 'rgb(68, 68, 68)'), ...
    'yaxis', struct(...                                        % y axis 1 % 
      'title', 'mbars', ...
      'titlefont', struct(...
        'family', '"Open sans", verdana, arial, sans-serif', ...
        'size', 14, ...
        'color', 'rgba(68, 68, 68, 0.49)'), ...
      'range', [1000, 1015], ...
      'domain', [0, 0.28], ...
      'type', 'linear', ...
      'rangemode', 'normal', ...
      'autorange', false, ...
      'showgrid', true, ...
      'zeroline', true, ...
      'showline', true, ...
      'nticks', 0, ...
      'ticks', 'outside', ...
      'showticklabels', true, ...
      'tickcolor', 'rgba(68, 68, 68, 0.49)', ...
      'tickangle', 'auto', ...
      'tickfont', struct(...
        'family', '"Open sans", verdana, arial, sans-serif', ...
        'size', 12, ...
        'color', 'rgba(68, 68, 68, 0.49)'), ...
      'exponentformat', 'B', ...
      'showexponent', 'all', ...
      'gridcolor', 'rgba(68, 68, 68, 0.49)', ...
      'gridwidth', 0.1, ...
      'zerolinecolor', '#444', ...
      'zerolinewidth', 1, ...
      'linecolor', 'rgb(68, 68, 68)'), ...
    'legend', struct(...
      'x', 0.794701986755, ...
      'y', 1.07456140351, ...
      'traceorder', 'normal', ...
      'font', struct(...
        'family', '"Open sans", verdana, arial, sans-serif', ...
        'size', 12, ...
        'color', '#444'), ...
      'bgcolor', '#fff', ...
      'bordercolor', '#444', ...
      'borderwidth', 0), ...
    'margin', struct('pad', 0), ...
    'paper_bgcolor', '#fff', ...
    'plot_bgcolor', '#fff', ...
    'hovermode', 'x', ...
    'dragmode', 'zoom', ...
    'separators', '.,', ...
    'hidesources', false, ...
    'yaxis2', struct(...                                       % y axis 2 %
      'title', 'mm', ...
      'titlefont', struct(...
        'family', '"Open sans", verdana, arial, sans-serif', ...
        'size', 14, ...
        'color', 'rgb(5, 10, 172)'), ...
      'range', [0, 10], ...
      'type', 'linear', ...
      'rangemode', 'normal', ...
      'autorange', false, ...
      'showgrid', true, ...
      'zeroline', true, ...
      'showline', true, ...
      'nticks', 0, ...
      'ticks', 'outside', ...
      'showticklabels', true, ...
      'tickcolor', 'rgb(5, 10, 172)', ...
      'tickangle', 'auto', ...
      'tickfont', struct(...
        'family', '"Open sans", verdana, arial, sans-serif', ...
        'size', 12, ...
        'color', 'rgb(5, 10, 172)'), ...
      'exponentformat', 'B', ...
      'showexponent', 'all', ...
      'gridcolor', 'rgb(5, 10, 172)', ...
      'gridwidth', 0.4, ...
      'zerolinecolor', 'rgb(5, 10, 172)', ...
      'zerolinewidth', 0.4, ...
      'linecolor', 'rgb(68, 68, 68)', ...
      'anchor', 'x', ...
      'overlaying', 'y', ...
      'side', 'right'), ...
    'yaxis3', struct(...                                       % y axis 3 %
      'title', '&deg;C', ...
      'titlefont', struct(...
        'family', '"Open sans", verdana, arial, sans-serif', ...
        'size', 14, ...
        'color', 'rgb(224, 102, 102)'), ...
      'range', [8.84804709078, 32.7519529092], ...
      'domain', [0.6, 0.88], ...
      'type', 'linear', ...
      'rangemode', 'normal', ...
      'autorange', true, ...
      'showgrid', true, ...
      'zeroline', true, ...
      'showline', true, ...
      'nticks', 0, ...
      'ticks', '', ...
      'showticklabels', true, ...
      'tickangle', 'auto', ...
      'tickfont', struct(...
        'family', '"Open sans", verdana, arial, sans-serif', ...
        'size', 12, ...
        'color', 'rgb(221, 126, 107)'), ...
      'exponentformat', 'B', ...
      'showexponent', 'all', ...
      'gridcolor', 'rgb(224, 102, 102)', ...
      'gridwidth', 0.1, ...
      'zerolinecolor', 'rgb(224, 102, 102)', ...
      'zerolinewidth', 0.4, ...
      'linecolor', 'rgb(68, 68, 68)', ...
      'anchor', 'x'), ...
    'yaxis5', struct(...                                       % y axis 5 %
      'title', 'km/h', ...
      'titlefont', struct('color', 'rgb(69, 129, 142)'), ...
      'range', [-0.00865655496649, 4.30865655497], ...
      'domain', [0.3, 0.58], ...
      'type', 'linear', ...
      'autorange', true, ...
      'showline', true, ...
      'tickfont', struct('color', 'rgb(69, 129, 142)'), ...
      'linecolor', 'rgb(68, 68, 68)', ...
      'anchor', 'x'), ...
    'yaxis7', struct(...                                       % y axis 7 %
      'title', '%', ...
      'titlefont', struct('color', 'rgb(61, 133, 198)'), ...
      'range', [0, 100], ...
      'type', 'linear', ...
      'autorange', false, ...
      'zeroline', true, ...
      'showline', true, ...
      'ticks', 'outside', ...
      'tickcolor', 'rgb(159, 197, 232)', ...
      'tickfont', struct('color', 'rgb(61, 133, 198)'), ...
      'zerolinecolor', 'rgb(207, 226, 243)', ...
      'linecolor', 'rgb(68, 68, 68)', ...
      'anchor', 'free', ...
      'overlaying', 'y', ...
      'side', 'left', ...
      'position', 0.18), ...
    'yaxis8', struct(...                                       % y axis 8 %
      'title', '&deg;E of N', ...
      'titlefont', struct('color', 'rgb(194, 123, 160)'), ...
      'range', [-30.0314485913, 390.031448591], ...
      'type', 'linear', ...
      'autorange', true, ...
      'showline', true, ...
      'tickfont', struct('color', 'rgb(194, 123, 160)'), ...
      'linecolor', 'rgb(68, 68, 68)', ...
      'anchor', 'x', ...
      'overlaying', 'y5', ...
      'side', 'right', ...
      'position', 0), ...
    'yaxis4', struct(...                                       % y axis 4 %
      'title', 'W/m^2', ...
      'titlefont', struct('color', 'rgb(241, 194, 50)'), ...
      'range', [0.0219861949583, 4.36101380504], ...
      'type', 'linear', ...
      'autorange', true, ...
      'showline', true, ...
      'ticks', 'outside', ...
      'tickcolor', 'rgb(241, 194, 50)', ...
      'tickfont', struct('color', 'rgb(241, 194, 50)'), ...
      'gridcolor', 'rgb(241, 194, 50)', ...
      'gridwidth', 0.1, ...
      'zerolinecolor', 'rgb(241, 194, 50)', ...
      'zerolinewidth', 0.4, ...
      'linecolor', 'rgb(68, 68, 68)', ...
      'anchor', 'x', ...
      'overlaying', 'y3', ...
      'side', 'right'));

Weather = plotly(data, struct('filename','OGSIR Weather','layout',layout,'fileopt',...
    'overwrite'));              % replace 'overwrite' with 'extend' to add data to dataset
                                % Format: plotly(data, struct('filename', filename,'layout', layout,'fileopt',fileopt));
plot_url = Weather.url

diary off                                                       % end logging

exit

% %%Notes: Alternative live-streaming method I could never get working
%
% %----STORED STREAMING CREDENTIALS----%
% my_credentials = loadplotlycredentials;
% my_stream_token = my_credentials.stream_ids{end};
% 
% %----SETUP-----%
% 
% data{1}.x = [];
% data{1}.y = [];
% data{1}.type = 'scatter';
% data{1}.stream.token = my_stream_token;
% data{1}.stream.maxpoints = 30;
% args.filename = 'MY_FIRST_STREAM';
% args.fileopt = 'overwrite';
% 
% %----PLOTLY-----%
% 
% resp = plotly(data,args);
% URL_OF_PLOT = resp.url

%eof